# Python makefile

.PHONY : run view

prob1: problem1.py heap.py
		@chmod u+x heap.py
		@chmod u+x problem1.py
		python problem1.py
		@echo

run : prob1

view : heap.py problem1.py
		@\less heap.py
		@\less problem1.py


